# Generated by Django 3.2.18 on 2023-06-03 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLineActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Baseline_activity',
            },
        ),
        migrations.CreateModel(
            name='Bmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('max_range', models.FloatField()),
                ('min_range', models.FloatField()),
            ],
            options={
                'db_table': 'Bmi',
            },
        ),
        migrations.CreateModel(
            name='DailyMealRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('day', models.CharField(max_length=20)),
                ('total_calories', models.DecimalField(decimal_places=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Daily_meal_record',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('food_type', models.CharField(max_length=200)),
                ('service_size', models.CharField(max_length=200)),
                ('calories', models.DecimalField(decimal_places=0, max_digits=10)),
                ('is_vegetarian_food', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Food',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Goal',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('dietary_restriction', models.CharField(choices=[('vegetarian', 'vegetarian'), ('free', 'free')], max_length=20)),
                ('baseline_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caloriesms.baselineactivity')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caloriesms.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='FoodDailyMealRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_meal_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caloriesms.dailymealrecord')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caloriesms.food')),
            ],
            options={
                'db_table': 'Food_daily_meal_record',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calories_burned_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bmi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caloriesms.bmi')),
            ],
            options={
                'db_table': 'Exercise',
            },
        ),
        migrations.CreateModel(
            name='BmiGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.DecimalField(decimal_places=0, max_digits=10)),
                ('baseline_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caloriesms.baselineactivity')),
                ('bmi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caloriesms.bmi')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caloriesms.goal')),
            ],
            options={
                'db_table': 'Bmi_goal',
            },
        ),
    ]
