# Generated by Django 3.2.18 on 2023-06-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloriesms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dietary_restriction',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non Vegetarian', 'Non Vegetarian')], max_length=20),
        ),
    ]
