# Generated by Django 3.2.18 on 2023-06-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloriesms', '0002_alter_profile_dietary_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymealrecord',
            name='total_calories',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
